select * from KOPO_PRODUCT_VOLUME;


SELECT *
FROM KOPO_PROMOTION
WHERE 1 = 1
AND TARGETWEEK
    BETWEEN &HK_START AND &HK_END;
    
    
    SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY YEARWEEK DESC;


select A.*,
       --LOWER(소문자변화) UPPER(대문자 변화)--
       CASE WHEN LOWER(A.gender) = 'Not Avaulable'
       then 0
       when UPPER(A.gender) = 'MALE'
       then 1
       else 2 end as sort_order
from kopo_customerdata A
order by sort_order;
--뒤에 desc 내림차순 //asc 오름차순--디폴트는 오름차순


select 
       REGIONID
     , PRODUCTGROUP
     , YEARWEEK
from KOPO_PRODUCT_VOLUME
order by YEARWEEK;


--UNION(합집합)--
SELECT * 
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
    UNION
SELECT * 
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0002';
--컬럼의 갯수와 순서가 같아야 한다



--INTERSECT(교집합)--
SELECT YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
INTERSECT
SELECT YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0002';


-- MINUS (차집합)
SELECT YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
MINUS
SELECT YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0002';


SELECT *
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
MINUS(
        SELECT YEARWEEK
        FROM KOPO_PRODUCT_VOLUME
        WHERE wearweek between 201501 and 201552
);

SELECT *
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
and yearweek not in(
        SELECT DISTINCT yearweek
        FROM KOPO_CHANNEL_PESULT_NEW
);


